get math question from beastie
carriebarrett/math_go pull request #41
Opened 2022-05-22 22:10 UTC by wozniakrach

- question popup now contains beastie question
- updated battle screen to contain image of beastie instead of text button

2022-05-24 01:16 UTC, cwrmadcat requested changes
Your code is failing linting because you are passing data to state objects (in this case beastie).  If you need access to beastie, use widget (i.e. widget.beastie).  

Here are some reference links:

https://dart-lang.github.io/linter/lints/no_logic_in_create_state.html
https://stackoverflow.com/questions/70445918/dont-put-any-logic-in-createstate-after-installing-flutter-lints-in-flutter

2022-05-24 03:55 UTC, carriebarrett requested changes
You don't need to pass anything from BattleScreen to BattleScreenState, you can access the beastie member of BattleScreen within BattleScreenState as widget.beastie. I haven't tested it but these are the changes I think are necessary: 
line 19 should be changed to 
```
State<BattleScreen> createState() => _BattleScreenState();
```
lines 25-27 should be removed
line 80 should be changed to
```
widget.beastie.question,
```
line 163 should be changed to 
```
widget.beastie.imagePath,
```

2022-05-25 04:29 UTC, cwrmadcat approved these changes
Looks good.

2022-05-25 19:48 UTC, carriebarrett approved these changes

2022-05-25 20:49 UTC, merged