Use collected beasties
carriebarrett/math_go pull request #42
Opened 2022-05-22 22:32 UTC by jorellana28

2022-05-22 22:55 UTC, wozniakrach approved these changes, later dismissed
Thanks for getting this to work, I was having issues.
- collection now specified from map screen
- currently using the first read collection for screen

2022-05-25 02:12 UTC, landreja requested changes

2022-05-25 02:12 UTC, landreja commented on lib/screens/map_view.dart
> +        (navigationArgs as Map<String, String>)['collectionId'];
I keep getting the below error when logging in with google on the last tutorial page or answering a math question correctly for the existing account. 
"_CastError (type 'Null' is not a subtype of type 'Map<String, String>' in type cast)"

2022-05-25 03:53 UTC, landreja approved these changes
- Google login works great, 
- beastie correct answer adds to database 
- beasties do not disappearing
-  correct answer the name and image do display in the collection screen 
- All beasties are updating Racheals collection  
- Text for name of beasties displays for both correct and incorrect answers at the bottom of the map_view screen.

2022-05-25 04:17 UTC, merged